apiVersion: v1
kind: Namespace
metadata:
  name: spark-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-runner
  namespace: spark-operator

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-runner-role
  namespace: spark-operator
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "persistentvolumeclaims"]
    verbs: ["create", "get", "list", "watch", "delete", "update", "deletecollection"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-runner-rolebinding
  namespace: spark-operator
subjects:
  - kind: ServiceAccount
    name: spark-runner
    namespace: spark-operator
roleRef:
  kind: Role
  name: spark-runner-role
  apiGroup: rbac.authorization.k8s.io
