apiVersion: skaffold/v3
kind: Config
metadata:
  name: spark-minio-k8s
build:
  local:
    concurrency: 0
  artifacts:
    - image: wcygan/spark-minio-k8s-spark-application
      context: spark-application
      docker:
        dockerfile: Dockerfile
#    - image: wcygan/spark-minio-k8s-writer
#      context: writer
#      docker:
#        dockerfile: Dockerfile
#    - image: wcygan/spark-minio-k8s-reader
#      context: reader
#      docker:
#        dockerfile: Dockerfile
deploy:
  helm:
    releases:
      - name: spark-operator
        repo: "https://googlecloudplatform.github.io/spark-on-k8s-operator"
        remoteChart: spark-operator
        namespace: spark-operator
        createNamespace: true
manifests:
  rawYaml:
    - admin.yaml
    - service-account.yaml
    - minio/pv.yaml
    - minio/pvc.yaml
    - minio/deployment.yaml
    - spark-application/spark-application.yaml
#    - reader/reader.yaml
#    - writer/writer.yaml