apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: spark-minio-k-s
build:
  artifacts:
    - image: wcygan/spark-minio-k8s-spark-application
      context: spark-application
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - admin.yaml
    - service-account.yaml
    - minio/deployment.yaml
    - minio/pv.yaml
    - minio/pvc.yaml
    - spark-application/spark-application.yaml
