apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-minio-k8s
  namespace: spark-operator
spec:
  type: Scala
  mode: cluster
  image: "wcygan/spark-minio-k8s-spark-application:latest"
  mainClass: "org.example.App"
  mainApplicationFile: "local:///opt/bitnami/spark/jars/spark-application.jar"
  sparkVersion: "3.3.4"
  restartPolicy:
    type: Never
  driver:
    cores: 2
    memory: "1g"
    labels:
      version: 3.3.4
    serviceAccount: spark-operator
  executor:
    cores: 2
    instances: 1
    memory: "2g"
    labels:
      version: 3.3.4
  sparkConf:
    "spark.kubernetes.executor.deleteOnTermination": "false"